fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.2.0'
    wget:
      repo: 'git://github.com/maestrodev/puppet-wget.git'
      ref: 'v1.2.2'
    logrotate:
      repo: 'git://github.com/voxpupuli/puppet-logrotate.git'
      ref: 'v2.0.0'
    puppi:
      repo: 'git://github.com/example42/puppi.git'
      ref:  'v2.1.10'
    java:
      repo: 'git://github.com/puppetlabs/puppetlabs-java'
      ref:  '1.1.1'
  symlinks:
    selenium: "#{source_dir}"
